name: Build & Deploy Flutter Web to main/docs

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y git wget unzip xz-utils curl

    - name: Setup Flutter
      run: |
        if [ ! -d "./flutter" ]; then
          git clone https://github.com/flutter/flutter.git -b stable
        fi
        ./flutter/bin/flutter --version
        ./flutter/bin/flutter config --enable-web
        ./flutter/bin/flutter pub get

    - name: Build web using script
      run: ./run_flutter.sh

    - name: Copy web build to docs
      run: |
        rm -rf docs
        cp -r build/web docs

    - name: Commit and push to main
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add docs
        git commit -m "Deploy Flutter web to docs [ci skip]" || echo "No changes to commit"
        git push
